// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ntgrzgunntvhpbtwzeec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50Z3J6Z3VubnR2aHBidHd6ZWVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0OTAwNTQsImV4cCI6MjA5MzA2NjA1NH0.g3ogCkH52PpIalc-kiLi6mGVAzxN8CYsNk7MTUhnjdM";

// Import the supabase client like this:
// import { supabase } from "@/src/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);